// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6oc82VJrrGvNKmvx5u0gKQLteGX0EC2M',
    appId: '1:755906876747:web:5498ea0494cba9aaa004ce',
    messagingSenderId: '755906876747',
    projectId: 'grcshpapp',
    authDomain: 'grcshpapp.firebaseapp.com',
    storageBucket: 'grcshpapp.appspot.com',
    measurementId: 'G-6YXVGHS2KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtEUXkiUI21oNGZsvv-IYxQwSNse3CP8',
    appId: '1:755906876747:android:747c2fcb84260515a004ce',
    messagingSenderId: '755906876747',
    projectId: 'grcshpapp',
    storageBucket: 'grcshpapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnef1vyzzQ_OtIuU8KhttNha1B9F8AKxE',
    appId: '1:755906876747:ios:7145af9a70213cdfa004ce',
    messagingSenderId: '755906876747',
    projectId: 'grcshpapp',
    storageBucket: 'grcshpapp.appspot.com',
    iosBundleId: 'com.example.groceryShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnef1vyzzQ_OtIuU8KhttNha1B9F8AKxE',
    appId: '1:755906876747:ios:7145af9a70213cdfa004ce',
    messagingSenderId: '755906876747',
    projectId: 'grcshpapp',
    storageBucket: 'grcshpapp.appspot.com',
    iosBundleId: 'com.example.groceryShoppingApp',
  );
}
